[package]
name = "codetime"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
